### ISSUE TITLE
Wallets stopped syning

### ISSUE THREAD

**Issue by wellenreiter01** [hank/feathercoin-wallet#11]
The Android Wallets stopped to sync several days ago.

As this was reported by several users, there is a possibility of a sorfware problem

see: https://forum.feathercoin.com/index.php?/topic/6830-android-wallet-stopped-syncing/

**Comment by ssrossbr** [comment]
I have the same problem since 8 days ago. My wallet can't sync anymore.

**Comment by GENiALi** [comment]
I have the same problem.
